version: "3"
services:
  db:
    image: postgres:9.6@sha256:75dfa422ab8704be73e238f52d1f921d6e178971d955e7b64c597096f41473e4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
  caluma:
    image: projectcaluma/caluma:latest@sha256:e7ee324d8aacb665409a88b09a874a2e12118d227982ca2f020c7a3365c5cc28
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
